"""empty message

Revision ID: ad4ae085befa
Revises: 
Create Date: 2022-09-02 16:51:21.189846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4ae085befa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_webhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('webhook', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('announce_player_connect', sa.Boolean(), nullable=False),
    sa.Column('announce_player_disconnect', sa.Boolean(), nullable=False),
    sa.Column('announce_player_buffer_time', sa.Integer(), nullable=False),
    sa.Column('announce_server_start', sa.Boolean(), nullable=False),
    sa.Column('announce_server_shutdown', sa.Boolean(), nullable=False),
    sa.Column('announce_update_success', sa.Boolean(), nullable=False),
    sa.Column('announce_update_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discord_webhook')
    # ### end Alembic commands ###
